name: habit_tracker
description: A beautiful neumorphic habit tracker app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0
  shared_preferences: ^2.2.2
  uuid: ^4.4.0
  flutter_local_notifications: ^19.4.2
  intl: ^0.20.2
  timezone: ^0.10.1
  # Backend Integration
  supabase_flutter: ^2.5.6
  http: ^1.2.2
  dio: ^5.7.0
  flutter_dotenv: ^5.1.0
  # State Management
  provider: ^6.1.2
  # JSON Serialization
  json_annotation: ^4.9.0
  # Haptic Feedback
  vibration: ^3.1.3
  # Voice Commands
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true